package icu.fuck.blued.constant

object ClassName {
    const val USER_INFO = "com.blued.android.module.common.user.model.UserInfo"
    const val LOGIN_RESULT = "com.blued.android.module.common.user.model.BluedLoginResult"
    const val MSG_CHATTING_PRESENT = "com.soft.blued.ui.msg.presenter.MsgChattingPresent"
    const val FLEX_DEBUG_SEV_CONFIG = "com.blued.android.config.FlexDebugSevConfig"
    const val VISITOR_LIST_ADAPTER = "com.soft.blued.ui.find.adapter.VisitorListAdapter"
    const val VISITOR_LIST_RECYCLE_VIEW_ADAPTER = "com.soft.blued.ui.find.adapter.VisitorListRecycleViewAdapter"
    const val FLASH_PHOTO_MANAGER = "com.soft.blued.ui.msg.manager.FlashPhotoManager"
    const val FLASH_NUMBER_MODEL = "com.soft.blued.ui.msg.model.FlashNumberModel"
    const val PRIVATE_CHAT_CONTROLLER = "com.blued.android.chat.grpc.core.chat.PrivateChatController"
    const val CHATTING_MODEL = "com.blued.android.chat.model.ChattingModel"
    const val MSG_CHATTING_ADAPTER = "com.soft.blued.ui.msg.adapter.MsgChattingAdapter"
    const val CHAT_HELPER_V4 = "com.soft.blued.ui.msg.controller.tools.ChatHelperV4"
    const val STATISTIC_BIZ_CLIENT = "com.blued.android.statistics.biz.Client"
    const val MINE_NEW_FRAGMENT = "com.soft.blued.ui.mine.fragment.MineNewFragment"
    const val MINE_PAGE_MODEL = "com.soft.blued.ui.mine.model.MinePageModel"
    const val HOME_ACTIVITY = "com.soft.blued.ui.home.HomeActivity"
    const val LOGIN_REGISTER_HTTP_UTILS = "com.soft.blued.http.LoginRegisterHttpUtils"
    const val AD_UTILS = "com.soft.blued.utils.ADUtils"
    const val TOAST_UTILS = "com.blued.android.module.common.utils.ToastUtils"
    const val AD_DOWNLOAD_MANAGER = "com.soft.blued.utils.AdDownloadManager"
    const val BLUED_UI_HTTP_RESPONSE = "com.blued.android.framework.http.BluedUIHttpResponse"
    const val I_REQUEST_HOST = "com.blued.android.core.net.IRequestHost"
}